spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/eipp
    username: svc1
    password: svc1
  flyway:
    enabled: true

logging:
  level:
    org.hibernate:
      SQL: debug
      # uncomment to see values for binding variables
      # type.descriptor.sql: trace
    org.vino9.eipp: debug

camel:
  springboot:
    main-run-controller: true

presentment-sender:
  poll-delay: 3000
  output-batch-size: 10
  max-output-size: 100
  output-path: /Users/lee/tmp/pse
