spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: validate
  datasource:
    url: "jdbc:h2:mem:test1"
  flyway:
    enabled: true
  h2:
    console.enabled: true

logging:
  level:
    org.hibernate:
      SQL: debug
      # uncomment to see values for binding variables
      # type.descriptor.sql: trace
    org.vino9.lib.batchdocreceiver: debug

batch-doc-processor:
  output-batch-size: 3