spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost/eipp
    username: svc1
    password: svc1
  flyway:
    enabled: true

camel:
  springboot:
    main-run-controller: true