spring:
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost/eipp
    username: svc1
    password: svc1
  flyway:
    enabled: true

logging:
  level:
    org.hibernate:
      SQL: debug
      # uncomment to see values for binding variables
      # type.descriptor.sql: trace
    org.vino9.lib.batchdocreceiver: debug

camel:
  springboot:
    main-run-controller: true

batch-doc-processor:
  output-batch-size: 10
  poll-delay: 5000
